### ISSUE TITLE
Broken links in team.html

### ISSUE THREAD

**Issue by jme52** [siesta-project/web-portal#1]
There are three broken links in the [About/team.html](https://siesta-project.github.io/web-portal/About/team.html) page: those to the websites of Profs. Gale, Ordejón and Soler.  They need to be updated in [_data/steering.yaml](../blob/aebdc478aec072d97bbc78369a96b49f6c30954a/_data/steering.yaml).

**Comment by albgar** [comment]
Fixed. Thanks.
